theme: jekyll-theme-cayman
title: "FLHA 2026 - The 1st Workshop on Federated Learning in Healthcare Applications"
description: 'Co-located with <a href="https://flics-conference.org/index.php" style="color: #000; text-decoration: none;">FLICS 2026</a>'
url: https://vnragavan.github.io
baseurl: "/flha-workshop-2026"
github:
  is_project_page: false
